credentials:
  usernames:
    demo_user:
      email: demo@example.com
      name: Demo User
      password: hashed_password_here
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name